// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/home/aiden/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/home/aiden/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/home/aiden/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/home/aiden/cortextos",
        CTX_PROJECT_ROOT: "/home/aiden/cortextos",
        CTX_ORG: process.env.CTX_ORG || "glv",
        PATH: "/home/aiden/.nvm/versions/node/v20.20.2/bin:" + (process.env.PATH || "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"),
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: 'npm',
      args: 'run dev',
      cwd: "/home/aiden/cortextos/dashboard",
      env: {
        PORT: process.env.PORT || '3000',
        PATH: "/home/aiden/.nvm/versions/node/v20.20.2/bin:" + (process.env.PATH || "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"),
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the npm process.
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
