// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/home/aiden/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/home/aiden/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/home/aiden/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/home/aiden/cortextos",
        CTX_PROJECT_ROOT: "/home/aiden/cortextos",
        CTX_ORG: process.env.CTX_ORG || "glv",
        // Debug-only: set to '1' to enable SIGUSR2 signal → controlled
        // uncaughtException for testing the crash-visibility path
        // (.daemon-crashed markers + crash-loop operator Telegram alert).
        // Leave '0' in production; enable temporarily to reproduce crash
        // paths during development. `kill -SIGUSR2 $(pm2 pid cortextos-daemon)`
        // then watch the operator chat for "🚨 CRITICAL: daemon crash-looping"
        // after 3 crashes in 15 min.
        CTX_DEBUG_ALLOW_CRASH_TRIGGER: '0',
      },
      // max_restarts + restart_delay is the ultimate crash-storm circuit
      // breaker. If the daemon dies 10 times faster than 5s apart, PM2
      // gives up — the fleet goes fully dead, requiring a manual
      // `pm2 restart cortextos-daemon`. That is intentional: storm
      // protection > fleet uptime during a pathological crash loop.
      // The daemon's uncaughtException handler (src/daemon/index.ts)
      // fires a Telegram alert to the operator at 3+ crashes in 15 min —
      // well before this circuit trips. Do NOT raise these values without
      // also strengthening the upstream fix; the 2026-04-22 storm is a
      // reminder that unchecked auto-restart amplifies one bug into a
      // fleet-wide outage.
      max_restarts: 10,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: 'npm',
      args: 'run dev',
      cwd: "/home/aiden/cortextos/dashboard",
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the npm process.
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
