import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    cli: 'src/cli/index.ts',
    daemon: 'src/daemon/index.ts',
    'hooks/hook-permission-telegram': 'src/hooks/hook-permission-telegram.ts',
    'hooks/hook-ask-telegram': 'src/hooks/hook-ask-telegram.ts',
    'hooks/hook-planmode-telegram': 'src/hooks/hook-planmode-telegram.ts',
    'hooks/hook-crash-alert': 'src/hooks/hook-crash-alert.ts',
    'hooks/hook-compact-telegram': 'src/hooks/hook-compact-telegram.ts',
    'hooks/hook-extract-facts': 'src/hooks/hook-extract-facts.ts',
    'hooks/hook-idle-flag': 'src/hooks/hook-idle-flag.ts',
    'hooks/hook-context-status': 'src/hooks/hook-context-status.ts',
    'social/scrape': 'src/social/scrape.ts',
    'social/scrapers/instagram': 'src/social/scrapers/instagram.ts',
    'social/scrapers/youtube': 'src/social/scrapers/youtube.ts',
    'social/scrapers/gbp': 'src/social/scrapers/gbp.ts',
    'social/scrapers/facebook': 'src/social/scrapers/facebook.ts',
    'social/scrapers/linkedin': 'src/social/scrapers/linkedin.ts',
    'social/scrapers/x': 'src/social/scrapers/x.ts',
    'social/scrapers/threads': 'src/social/scrapers/threads.ts',
    'social/scrapers/tiktok': 'src/social/scrapers/tiktok.ts',
    'social/scrapers/instagram-post': 'src/social/scrapers/instagram-post.ts',
    'social/weekly-summary': 'src/social/weekly-summary.ts',
    'social/post-tracker': 'src/social/post-tracker.ts',
    'social/channel-tracker': 'src/social/channel-tracker.ts',
  },
  format: ['cjs'],
  target: 'node20',
  clean: true,
  splitting: false,
  sourcemap: true,
  dts: false,
  shims: true,
  banner: {
    js: '#!/usr/bin/env node',
  },
  external: ['node-pty'],
});
