import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { parseEnvFile } from '../../../src/cli/dashboard.js';

describe('parseEnvFile', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'ctx-dashboard-test-'));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('returns {} for a missing file', () => {
    const result = parseEnvFile(join(tmpDir, 'nonexistent.env'));
    expect(result).toEqual({});
  });

  it('returns {} for an empty file', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(envPath, '', 'utf-8');
    expect(parseEnvFile(envPath)).toEqual({});
  });

  it('returns {} for a file with only comments and blank lines', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(envPath, '# comment\n\n# another comment\n', 'utf-8');
    expect(parseEnvFile(envPath)).toEqual({});
  });

  it('parses a plain KEY=VALUE line', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(envPath, 'AUTH_SECRET=mysecret123\n', 'utf-8');
    expect(parseEnvFile(envPath)).toEqual({ AUTH_SECRET: 'mysecret123' });
  });

  it('strips outer double quotes from the value', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(envPath, 'KEY="some value"\n', 'utf-8');
    expect(parseEnvFile(envPath)).toEqual({ KEY: 'some value' });
  });

  it('strips outer single quotes from the value', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(envPath, "KEY='some value'\n", 'utf-8');
    expect(parseEnvFile(envPath)).toEqual({ KEY: 'some value' });
  });

  it('preserves values containing = signs (only the first = splits)', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(envPath, 'TOKEN=abc=def=ghi\n', 'utf-8');
    expect(parseEnvFile(envPath)).toEqual({ TOKEN: 'abc=def=ghi' });
  });

  it('skips lines that have no key (= at position 0)', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(envPath, '=VALUE\n', 'utf-8');
    expect(parseEnvFile(envPath)).toEqual({});
  });

  it('skips lines that have no = sign', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(envPath, 'JUSTAKEYNOVALUE\n', 'utf-8');
    expect(parseEnvFile(envPath)).toEqual({});
  });

  it('parses multiple keys, skipping comments and blanks', () => {
    const envPath = join(tmpDir, 'test.env');
    writeFileSync(
      envPath,
      [
        '# Generated by cortextos install',
        'AUTH_SECRET=abc123',
        'ADMIN_USERNAME=admin',
        '',
        'ADMIN_PASSWORD="p@ssw0rd"',
        'CTX_ROOT=/home/user/.cortextos/default',
      ].join('\n') + '\n',
      'utf-8',
    );
    expect(parseEnvFile(envPath)).toEqual({
      AUTH_SECRET: 'abc123',
      ADMIN_USERNAME: 'admin',
      ADMIN_PASSWORD: 'p@ssw0rd',
      CTX_ROOT: '/home/user/.cortextos/default',
    });
  });
});
