import { describe, it, expect } from 'vitest';
import { buildDashboardBlock, buildEcosystemContent } from '../../../src/cli/ecosystem';

const BASE = {
  daemonScript: '/home/user/cortextos/dist/daemon.js',
  projectRoot: '/home/user/cortextos',
  ctxRoot: '/home/user/.cortextos/default',
  instance: 'default',
  detectedOrg: 'myorg',
  dashboardBlock: '',
};

describe('buildDashboardBlock', () => {
  it('starts with a comma so it appends cleanly after the daemon block', () => {
    expect(buildDashboardBlock('/p')).toMatch(/^,/);
  });

  it("contains name: 'cortextos-dashboard'", () => {
    expect(buildDashboardBlock('/p')).toContain("name: 'cortextos-dashboard'");
  });

  it("contains script: 'npm'", () => {
    expect(buildDashboardBlock('/p')).toContain("script: 'npm'");
  });

  it("contains args: 'run dev'", () => {
    expect(buildDashboardBlock('/p')).toContain("args: 'run dev'");
  });

  it('embeds dashboardDir via JSON.stringify for cwd', () => {
    const dir = '/home/user/cortextos/dashboard';
    expect(buildDashboardBlock(dir)).toContain(`cwd: ${JSON.stringify(dir)}`);
  });

  it('correctly quotes a dashboard dir containing spaces', () => {
    const dir = '/home/my project/cortextos/dashboard';
    const block = buildDashboardBlock(dir);
    expect(block).toContain(`cwd: "${dir}"`);
  });

  it("contains PORT: process.env.PORT || '3000'", () => {
    expect(buildDashboardBlock('/p')).toContain("PORT: process.env.PORT || '3000'");
  });

  it('contains max_restarts: 50', () => {
    expect(buildDashboardBlock('/p')).toContain('max_restarts: 50');
  });

  it('contains restart_delay: 5000', () => {
    expect(buildDashboardBlock('/p')).toContain('restart_delay: 5000');
  });

  it('contains autorestart: true', () => {
    expect(buildDashboardBlock('/p')).toContain('autorestart: true');
  });
});

describe('buildEcosystemContent', () => {
  it('contains the AUTO-GENERATED header', () => {
    expect(buildEcosystemContent(BASE)).toContain('AUTO-GENERATED by');
  });

  it('contains the re-run instruction', () => {
    expect(buildEcosystemContent(BASE)).toContain('Re-run `cortextos ecosystem` to regenerate.');
  });

  it('contains the process.env runtime note', () => {
    expect(buildEcosystemContent(BASE)).toContain(
      "env vars use process.env.X || 'default' so PM2 picks up the value",
    );
  });

  it('contains module.exports = {', () => {
    expect(buildEcosystemContent(BASE)).toContain('module.exports = {');
  });

  it('contains apps: [', () => {
    expect(buildEcosystemContent(BASE)).toContain('apps: [');
  });

  it("contains name: 'cortextos-daemon'", () => {
    expect(buildEcosystemContent(BASE)).toContain("name: 'cortextos-daemon'");
  });

  it('sets script to JSON.stringify(daemonScript)', () => {
    expect(buildEcosystemContent(BASE)).toContain(`script: ${JSON.stringify(BASE.daemonScript)}`);
  });

  it('embeds instance in the args line via process.env fallback', () => {
    expect(buildEcosystemContent(BASE)).toContain(
      `process.env.CTX_INSTANCE_ID || ${JSON.stringify(BASE.instance)}`,
    );
  });

  it('sets cwd to JSON.stringify(projectRoot)', () => {
    expect(buildEcosystemContent(BASE)).toContain(`cwd: ${JSON.stringify(BASE.projectRoot)}`);
  });

  it('sets CTX_INSTANCE_ID env with process.env fallback', () => {
    expect(buildEcosystemContent(BASE)).toContain(
      `CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || ${JSON.stringify(BASE.instance)}`,
    );
  });

  it('sets CTX_ROOT env with process.env fallback', () => {
    expect(buildEcosystemContent(BASE)).toContain(
      `CTX_ROOT: process.env.CTX_ROOT || ${JSON.stringify(BASE.ctxRoot)}`,
    );
  });

  it('sets CTX_FRAMEWORK_ROOT to JSON.stringify(projectRoot)', () => {
    expect(buildEcosystemContent(BASE)).toContain(
      `CTX_FRAMEWORK_ROOT: ${JSON.stringify(BASE.projectRoot)}`,
    );
  });

  it('sets CTX_PROJECT_ROOT to JSON.stringify(projectRoot)', () => {
    expect(buildEcosystemContent(BASE)).toContain(
      `CTX_PROJECT_ROOT: ${JSON.stringify(BASE.projectRoot)}`,
    );
  });

  it('sets CTX_ORG env with process.env fallback', () => {
    expect(buildEcosystemContent(BASE)).toContain(
      `CTX_ORG: process.env.CTX_ORG || ${JSON.stringify(BASE.detectedOrg)}`,
    );
  });

  it('daemon block contains max_restarts: 50', () => {
    expect(buildEcosystemContent(BASE)).toContain('max_restarts: 50');
  });

  it('daemon block contains restart_delay: 5000', () => {
    expect(buildEcosystemContent(BASE)).toContain('restart_delay: 5000');
  });

  it('excludes dashboard block when dashboardBlock is empty', () => {
    expect(buildEcosystemContent({ ...BASE, dashboardBlock: '' })).not.toContain('cortextos-dashboard');
  });

  it('includes dashboard block content when dashboardBlock is non-empty', () => {
    const dashboardBlock = buildDashboardBlock('/home/user/cortextos/dashboard');
    expect(buildEcosystemContent({ ...BASE, dashboardBlock })).toContain('cortextos-dashboard');
  });

  it('correctly quotes a daemon script path containing spaces', () => {
    const opts = { ...BASE, daemonScript: '/home/my user/cortextos/dist/daemon.js' };
    expect(buildEcosystemContent(opts)).toContain(
      `script: "/home/my user/cortextos/dist/daemon.js"`,
    );
  });

  it('ends with a newline', () => {
    expect(buildEcosystemContent(BASE)).toMatch(/\n$/);
  });

  it('instance value appears in both args and CTX_INSTANCE_ID env (propagation)', () => {
    const opts = { ...BASE, instance: 'production' };
    const result = buildEcosystemContent(opts);
    const hits = (result.match(/"production"/g) ?? []).length;
    expect(hits).toBeGreaterThanOrEqual(2);
  });

  it('different instance values produce different output (no cross-contamination)', () => {
    const r1 = buildEcosystemContent({ ...BASE, instance: 'prod' });
    const r2 = buildEcosystemContent({ ...BASE, instance: 'staging' });
    expect(r1).not.toBe(r2);
    expect(r1).toContain('"prod"');
    expect(r2).toContain('"staging"');
  });

  it('different orgs produce different output', () => {
    const r1 = buildEcosystemContent({ ...BASE, detectedOrg: 'glv' });
    const r2 = buildEcosystemContent({ ...BASE, detectedOrg: 'acme' });
    expect(r1).toContain('"glv"');
    expect(r2).toContain('"acme"');
    expect(r1).not.toContain('"acme"');
  });

  it('closes module.exports correctly', () => {
    const result = buildEcosystemContent(BASE);
    expect(result).toContain('\n};\n');
  });
});
