import { describe, it, expect } from 'vitest';
import { isValidGoalsName, buildGoalsMd } from '../../../src/cli/goals.js';

// --------------------------------------------------------------------
// isValidGoalsName
// --------------------------------------------------------------------

describe('isValidGoalsName', () => {
  it('accepts lowercase alpha', () => {
    expect(isValidGoalsName('dev')).toBe(true);
  });

  it('accepts mixed-case (goals command allows uppercase)', () => {
    expect(isValidGoalsName('Dev')).toBe(true);
  });

  it('accepts alphanumeric with hyphens and underscores', () => {
    expect(isValidGoalsName('my-org_123')).toBe(true);
  });

  it('accepts digits only', () => {
    expect(isValidGoalsName('123')).toBe(true);
  });

  it('rejects name with a space', () => {
    expect(isValidGoalsName('has space')).toBe(false);
  });

  it('rejects name with a dot', () => {
    expect(isValidGoalsName('has.dot')).toBe(false);
  });

  it('rejects name with a slash', () => {
    expect(isValidGoalsName('has/slash')).toBe(false);
  });

  it('rejects empty string (+ requires at least one char)', () => {
    expect(isValidGoalsName('')).toBe(false);
  });
});

// --------------------------------------------------------------------
// buildGoalsMd
// --------------------------------------------------------------------

describe('buildGoalsMd', () => {
  // --- Structure ---

  it('output starts with "# Goals"', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md.startsWith('# Goals\n')).toBe(true);
  });

  it('contains the auto-generated warning line', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md).toContain('> Auto-generated from goals.json. Do not edit this file directly.');
  });

  it('regenerate hint embeds agent and org names', () => {
    const md = buildGoalsMd({}, 'myagent', 'myorg');
    expect(md).toContain('--agent myagent --org myorg');
  });

  it('contains ## Focus section header', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md).toContain('## Focus');
  });

  it('contains ## Goals section header', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md).toContain('## Goals');
  });

  it('contains ## Bottleneck section header', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md).toContain('## Bottleneck');
  });

  it('contains ## Updated section header', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md).toContain('## Updated');
  });

  // --- Focus ---

  it('shows focus text when set', () => {
    const md = buildGoalsMd({ focus: 'ship the feature' }, 'dev', 'glv');
    expect(md).toContain('ship the feature');
  });

  it('shows fallback when focus is empty string', () => {
    const md = buildGoalsMd({ focus: '' }, 'dev', 'glv');
    expect(md).toContain('(not set — check with your orchestrator)');
  });

  it('shows fallback when focus is not a string (number)', () => {
    const md = buildGoalsMd({ focus: 42 }, 'dev', 'glv');
    expect(md).toContain('(not set — check with your orchestrator)');
  });

  it('shows fallback when focus is missing', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md).toContain('(not set — check with your orchestrator)');
  });

  // --- Bottleneck ---

  it('shows bottleneck text when set', () => {
    const md = buildGoalsMd({ bottleneck: 'waiting on Aiden review' }, 'dev', 'glv');
    expect(md).toContain('waiting on Aiden review');
  });

  it('shows "(none)" when bottleneck is missing', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md).toContain('(none)');
  });

  it('shows "(none)" when bottleneck is empty string', () => {
    const md = buildGoalsMd({ bottleneck: '' }, 'dev', 'glv');
    expect(md).toContain('(none)');
  });

  // --- Goals list ---

  it('shows empty-goals message when goals array is empty', () => {
    const md = buildGoalsMd({ goals: [] }, 'dev', 'glv');
    expect(md).toContain("(none set — message your orchestrator to request today's goals)");
  });

  it('shows empty-goals message when goals is not an array', () => {
    const md = buildGoalsMd({ goals: 'not-an-array' }, 'dev', 'glv');
    expect(md).toContain("(none set — message your orchestrator to request today's goals)");
  });

  it('shows empty-goals message when goals key is absent', () => {
    const md = buildGoalsMd({}, 'dev', 'glv');
    expect(md).toContain("(none set — message your orchestrator to request today's goals)");
  });

  it('numbers a single string goal starting at 1', () => {
    const md = buildGoalsMd({ goals: ['write tests'] }, 'dev', 'glv');
    expect(md).toContain('1. write tests');
  });

  it('numbers multiple string goals sequentially', () => {
    const md = buildGoalsMd({ goals: ['alpha', 'beta', 'gamma'] }, 'dev', 'glv');
    expect(md).toContain('1. alpha');
    expect(md).toContain('2. beta');
    expect(md).toContain('3. gamma');
  });

  it('extracts title from object goals', () => {
    const md = buildGoalsMd({ goals: [{ title: 'Ship PR #27' }] }, 'dev', 'glv');
    expect(md).toContain('1. Ship PR #27');
  });

  it('handles mixed string and object goals', () => {
    const md = buildGoalsMd(
      { goals: ['plain string', { title: 'object title' }] },
      'dev',
      'glv',
    );
    expect(md).toContain('1. plain string');
    expect(md).toContain('2. object title');
  });

  // --- Updated ---

  it('formats Updated line as "<date> (by <name>)" when both are present', () => {
    const md = buildGoalsMd(
      { updated_at: '2026-04-28', updated_by: 'Aiden' },
      'dev',
      'glv',
    );
    expect(md).toContain('2026-04-28 (by Aiden)');
  });

  it('formats Updated line as just the date when updated_by is absent', () => {
    const md = buildGoalsMd({ updated_at: '2026-04-28' }, 'dev', 'glv');
    expect(md).toContain('2026-04-28');
    expect(md).not.toContain('(by');
  });

  it('falls back to a fresh ISO timestamp when updated_at is not a string', () => {
    const md = buildGoalsMd({ updated_at: null }, 'dev', 'glv');
    // The fallback is new Date().toISOString() — just verify it looks like an ISO date
    expect(md).toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  // --- Full output shape ---

  it('produces the expected section ordering', () => {
    const md = buildGoalsMd(
      { focus: 'f', goals: ['g1'], bottleneck: 'b', updated_at: '2026-04-28', updated_by: 'X' },
      'agent',
      'org',
    );
    const focusIdx = md.indexOf('## Focus');
    const goalsIdx = md.indexOf('## Goals');
    const bottleneckIdx = md.indexOf('## Bottleneck');
    const updatedIdx = md.indexOf('## Updated');
    expect(focusIdx).toBeLessThan(goalsIdx);
    expect(goalsIdx).toBeLessThan(bottleneckIdx);
    expect(bottleneckIdx).toBeLessThan(updatedIdx);
  });
});
